version: "3"

services:
  # Your other services.

  gotenberg:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=20"
      - "--api-timeout=1300s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg2:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=40"
      - "--api-timeout=1310s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg3:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=80"
      - "--api-timeout=1320s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg4:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=120"
      - "--api-timeout=1330s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg5:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=160"
      - "--api-timeout=1400s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg6:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=180"
      - "--api-timeout=1500s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg7:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=200"
      - "--api-timeout=1600s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  gotenberg8:
    image: gotenberg/gotenberg:8
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=250"
      - "--api-timeout=1700s"
      - "--libreoffice-auto-start=true"
    networks:
      - gotenberg_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

  nginx:
    image: nginx:latest
    ports:
      - "7000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - gotenberg
      - gotenberg2
      - gotenberg3
      - gotenberg4
      - gotenberg5
      - gotenberg6
      - gotenberg7
      - gotenberg8
    networks:
      - gotenberg_net

networks:
  gotenberg_net:
    driver: bridge
