version: "3"

services:
  # Your other services.

  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "7000:3000"
    restart: always
    command:
      - "gotenberg"
      - "--libreoffice-restart-after=0"
      - "--libreoffice-auto-start=true"
    networks:
      - my_net
    volumes:
      - ./fonts:/usr/local/share/fonts:ro

networks:
  my_net:
    driver: bridge
